[global]
developmentMode = false

[server]
port = 8501
address = "0.0.0.0"
headless = true
runOnSave = true
allowRunOnSave = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
primaryColor = "#ff6900"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[logger]
level = "info"